# Generated by Django 5.1 on 2024-08-26 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasksApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='detecompleted',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='important',
            field=models.IntegerField(default=False, null=True),
        ),
    ]
