# Generated by Django 5.1 on 2024-08-26 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasksApp', '0002_alter_task_detecompleted_alter_task_important'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='important',
            field=models.IntegerField(blank=True, default=False, null=True),
        ),
    ]
