# Generated by Django 5.1 on 2024-08-26 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasksApp', '0003_alter_task_important'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(max_length=100),
        ),
    ]
